name = "Rust Macros Working Group"
description = "Meetings for the macros working group"

[[events]]
uid = "1704471175975"
title = "wg-macros Sync Meeting"
description = "Biweekly sync meeting of the macros working group"
location = "#wg-macros on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/404510-wg-macros)"
last_modified_on = "2024-01-05T16:06:00.00Z"
start = "2024-01-05T16:00:00.00Z"
end = "2024-01-05T17:00:00.00Z"
status = "confirmed"
organizer = { name = "wg-macros", email = "compiler@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 2 } ]

[[events]]
uid = "1704471162252"
title = "wg-macros Triage Meeting"
description = "Biweekly triage meeting of the macros working group"
location = "#wg-macros/triage on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/410876-wg-macros.2Ftriage)"
last_modified_on = "2024-01-05T16:08:00.00Z"
start = "2024-01-12T16:00:00.00Z"
end = "2024-01-12T17:00:00.00Z"
status = "confirmed"
organizer = { name = "wg-macros", email = "compiler@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 2 } ]
